# Generated by Django 6.0.4 on 2026-04-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(default="Informatica de Gestao", max_length=100),
                ),
                ("ano_inicio", models.IntegerField(default=2024)),
                ("ano_previsto_fim", models.IntegerField(default=2027)),
                (
                    "instituicao",
                    models.CharField(default="Universidade Lusófona", max_length=100),
                ),
            ],
        ),
    ]
