# Generated by Django 6.0.4 on 2026-04-11 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("instituicao", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
                ("descricao", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                (
                    "fotos",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/makingof/"
                    ),
                ),
                ("erros", models.TextField(blank=True, null=True)),
                ("decisoes", models.TextField(blank=True, null=True)),
                (
                    "entidade_relacionada",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/tecnologias/"
                    ),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("nivel_interesse", models.IntegerField(default=0)),
                ("descricao", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("conceitos", models.TextField()),
                (
                    "imagem",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/projeto_images/"
                    ),
                ),
                ("video_demo", models.URLField(blank=True, null=True)),
                ("github", models.URLField(blank=True, null=True)),
                (
                    "tecnologias",
                    models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "formacoes",
                    models.ManyToManyField(blank=True, to="portfolio.formacao"),
                ),
                (
                    "projetos",
                    models.ManyToManyField(blank=True, to="portfolio.projeto"),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("ano", models.IntegerField()),
                ("interesse", models.IntegerField(default=0)),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tfcs",
                        to="portfolio.licenciatura",
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("codigo", models.CharField(max_length=20)),
                ("ano", models.IntegerField()),
                ("semestre", models.IntegerField()),
                (
                    "imagem",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/uc_images/"
                    ),
                ),
                ("docente", models.CharField(max_length=100)),
                ("pagina_docente", models.URLField(blank=True, null=True)),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ucs",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projeto",
            name="unidade_curricular",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projetos",
                to="portfolio.unidadecurricular",
            ),
        ),
    ]
