# Generated by Django 6.0.4 on 2026-04-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0002_formacao_makingof_tecnologia_projeto_competencia_tfc_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="licenciatura",
            name="descricao",
            field=models.TextField(blank=True, default="", max_length=2000),
        ),
    ]
